/**
 * @license Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
 */

/* exported CKBUILDER_CONFIG */

var CKBUILDER_CONFIG = {
	skin: 'moono-lisa',
	ignore: [
		'bender.js',
		'bender.ci.js',
		'.bender',
		'bender-err.log',
		'bender-out.log',
		'.travis.yml',
		'dev',
		'docs',
		'.DS_Store',
		'.editorconfig',
		'.gitignore',
		'.gitattributes',
		'.github',
		'gruntfile.js',
		'.idea',
		'.jscsrc',
		'.jshintignore',
		'.jshintrc',
		'less',
		'.mailmap',
		'.nvmrc',
		'node_modules',
		'package.json',
		'README.md',
		'tests'
	],
	plugins: {
		a11yhelp: 1,
		about: 0,
		basicstyles: 1,
		bidi: 0,
		blockquote: 1,
		clipboard: 1,
		colorbutton: 0,
		colordialog: 0,
		copyformatting: 0,
		contextmenu: 1,
		dialogadvtab: 0,
		div: 0,
		elementspath: 1,
		enterkey: 1,
		entities: 1,
		filebrowser: 0,
		find: 0,
		floatingspace: 1,
		font: 0,
		format: 1,
		forms: 0,
		horizontalrule: 1,
		htmlwriter: 1,
		iframe: 0,
		image: 1,
		indentlist: 1,
		indentblock: 0,
		justify: 0,
		language: 0,
		link: 1,
		list: 1,
		liststyle: 1,
		magicline: 1,
		maximize: 1,
		newpage: 0,
		pagebreak: 0,
		pastefromlibreoffice: 0,
		pastefromword: 1,
		pastetext: 1,
		editorplaceholder: 0,
		preview: 0,
		print: 0,
		removeformat: 1,
		resize: 1,
		save: 0,
		selectall: 0,
		showblocks: 0,
		showborders: 1,
		smiley: 0,
		sourcearea: 1,
		specialchar: 1,
		stylescombo: 1,
		tab: 1,
		table: 1,
		tableselection: 1,
		tabletools: 1,
		templates: 0,
		toolbar: 1,
		undo: 1,
		uploadimage: 0,
		wysiwygarea: 1
	}
};
